application: wm-selector
version: 1

api_version: 1
runtime: python27
threadsafe: true

skip_files:
- ^(?!dist).+

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /army_selector\.html(.*)
  static_files: dist/index.html
  upload: dist/index.html
- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)